## What does element-wise mean?
An element-wise process is a process where something happens "for each element". Python lists don't support element-wise processes, and so you have to program them yourself with a for loop. For example, if we wanted to add one to every number in a Python list, we could do the following:

In [1]:
# an example list of numbers
numbers = [2, -5, 6, 4, 1]

# adding one to each element
new_numbers = []
for number in numbers:
    new_numbers.append(number + 1)
    
new_numbers

[3, -4, 7, 5, 2]

NumPy does support element-wise processes. This makes it much simpler to program them and the code itself will run much faster. If we wanted to add one to every number in a NumPy array, we could do the following:

In [3]:
# an example array of numbers
import numpy as np
numbers = np.array([2, -5, 6, 4, 1])

# adding one to each element
numbers + 1

array([ 3, -4,  7,  5,  2])

***
## Element-wise operators
When operating with arrays, your standard mathematics operators will perform that operation element-wise.

If the operation involves **an array and a scalar**, the scalar operation will occur for each element in the array. For example, suppose we want to solve the following math problem which involves element-wise multiplication between a vector and a scalar:

\begin{pmatrix}
4 \\
2 \\
5
\end{pmatrix} \times 10 = \begin{pmatrix}
4 \times 10\\
2 \times 10\\
5 \times 10
\end{pmatrix} = \begin{pmatrix}
40\\
20\\
50
\end{pmatrix}

We could use the code:

In [4]:
np.array([4, 2, 5]) * 10

array([40, 20, 50])

If the operation involves **two arrays**, then they should have the same shape. The operation will occur on each pair of corresponding elements. For example, suppose we want to solve the following math problem which involves element-wise addition of two vectors:

\begin{pmatrix}
5 \\
2 \\
0
\end{pmatrix} + 
\begin{pmatrix}
7 \\
9 \\
4
\end{pmatrix} = 
\begin{pmatrix}
5 + 7 \\
2 + 9 \\
0 + 4
\end{pmatrix} = 
\begin{pmatrix}
12 \\
11 \\
4
\end{pmatrix}

We could use the code:

In [5]:
np.array([5, 2, 0]) + np.array([7, 9, 4])

array([12, 11,  4])

## Element-wise functions
Standard mathematical functions such as <code>sqrt</code>, <code>exp</code>, <code>log</code>, <code>sin</code> and <code>cos</code> are all stored within NumPy. These functions differ from those within the math module because they support element-wise application of the function.

For example, if we wanted to find the natural logarithm of each integer from 1 to 9. Using the <code>log</code> function from the <code>math</code> module, we would require a for loop.

In [7]:
import math
integers = range(1, 10)
log_integers = []
for integer in integers:
    log_integers.append(math.log(integer))
    
log_integers

[0.0,
 0.6931471805599453,
 1.0986122886681098,
 1.3862943611198906,
 1.6094379124341003,
 1.791759469228055,
 1.9459101490553132,
 2.0794415416798357,
 2.1972245773362196]

Using the <code>log</code> function from the <code>numpy</code> module offers a simpler alternative:

In [8]:
integers = np.arange(1, 10)
np.log(integers)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Element-wise comparison
When working with arrays, relational operators will perform element-wise comparison rather than a single comparison of the entire object. For example, consider the Boolean expression below between two lists. It outputs <code>False</code> since the list on the left is not equal to the list on the right.

In [9]:
# returns False since lists are compared holistically
[4, 2, 1] == [4, 5, 1]

False

If we look at the same expression using arrays, it returns the Boolean array <code>[True, False, True]</code>. It has performed the comparison on an element-wise basis rather than comparing the objects as a whole. The result indicates the first and third elements are the same, but the second element is different.

In [10]:
# returns [True, False, True] since arrays are compared on an element-wise basis
np.array([4, 2, 1]) == np.array([4, 5, 1])

array([ True, False,  True])

*** 
## Video summary