## Mathematics with NumPy
NumPy includes many functions and methods that are useful for more advanced mathematical problems. On this page, we highlight the functionality that is useful within EGD103 and other units within the Diploma of Engineering. 

***
## Statistics with NumPy
NumPy includes many functions to facilitate statistics. The main statistical functions you will use in this unit are summarised below.

|Function name	| Description |
| ------------- | ----------- |
|<code>np.mean</code>	| Find the average of each number. |
|<code>np.median</code>	| Find the middle number once placed in order from lowest to highest. |
|<code>np.std</code>	| Find the standard deviation (average spread) of the values. |
|<code>np.var</code>	| Find the variance (average spread squared) of the values. |
|<code>np.sum</code>	| Sum all the values. |
|<code>np.min</code>	| Find the minimum value. |
|<code>np.max</code>	| Find the maximum value. |

NumPy has an equivalent method for most of these functions. For example, if we wanted to find the average value in an array, we could call the mean function <code>np.mean(array_name)</code> or call the mean method <code>array_name.mean()</code>.

For higher-dimensional arrays, the aggregate will be performed for the entire object. If you want it to be performed along a single axis, then you require an axis argument.

In [3]:
# create an matrix of values
import numpy as np
matrix = np.array([[1, 2], [3, 4]])
matrix

array([[1, 2],
       [3, 4]])

In [4]:
# compute the mean of all values in a matrix
np.mean(matrix)

2.5

In [5]:
# compute the mean of each column of a matrix
np.mean(matrix, axis = 0)

array([2., 3.])

In [6]:
# compute the mean of each row in a matrix
np.mean(matrix, axis = 1)

array([1.5, 3.5])

For more statistics functionality, you can consult the documentation: https://numpy.org/doc/stable/reference/routines.statistics.html


***
## Linear algebra with NumPy
One of the most common uses for NumPy is working with vectors and matrices. Those of you learning this theory in EGD125 might find the following functionality useful. If you haven't studied EGD125 yet, I would encourage you to skip this page for now, and revisit it when you do study it.

|Operation	| Python code |
| ----------------- | ----------- |
|Matrix/vector addition	| <code>matrix_1 + matrix_2</code> |
|Matrix/vector subtraction	| <code>matrix_1 - matrix_2</code> |
|Scalar multiplication of matrix/vector	| <code>scalar * matrix_1</code> |
|Matrix multiplication	| <code>matrix_1 @ matrix_2</code> |
|Dot product	| <code>np.dot(vector_1, vector_2)</code> |
|Cross product	| <code>np.cross(vector_1, vector_2)</code>|
|Transpose	| <code>matrix_1.transpose()</code> |
|Determinant	| <code>np.linalg.det(matrix_1)</code>|
|Inverse	| <code>np.linalg.inv(matrix_1)</code> |
|Solving a system of linear equations: $A \mathbf{x} = b$
|<code>np.linalg.solve(A, b)</code> |

Each operation is subject to the shape restrictions - you will learn about these when you cover vectors and matrices in EGD125.

For more linear algebra functionality, you can consult the documentation: https://numpy.org/doc/stable/reference/routines.linalg.html


***
## Video summary