## Indexing and slicing for ID arrays
All of the indexing and slicing rules you learned for lists will also work for NumPy arrays. You can view the examples below for a refresher.

In [1]:
# creating an array of voltages
import numpy as np
voltages = np.array([3, 1, 5, 9, 2, 3, 6]) 

In [2]:
# getting the first voltage
voltages[0]

3

In [3]:
# getting the third voltage
voltages[2]

5

In [4]:
# getting the last voltage
voltages[-1]

6

In [5]:
# getting the first 3 voltages
voltages[:3]

array([3, 1, 5])

In [6]:
# getting the last 4 voltages
voltages[-4:]

array([9, 2, 3, 6])

In [7]:
# getting the 2nd to 5th voltages
voltages[1:5]

array([1, 5, 9, 2])

***
## Indexing and slicing for 2D (and higher) arrays
Since arrays have dimension associated with them, we have the added functionality of being able to provide an index or slice for each dimension. For a 2D array, the syntax is <code>array_name[row_index, col_index]</code>. Some examples are provided below.

In [9]:
# creating a 2D array of stresses
stresses = np.array([[500, 400, 200], [200, 100, 400], [250, 400, 350]])
stresses

array([[500, 400, 200],
       [200, 100, 400],
       [250, 400, 350]])

In [10]:
# getting the element in the third row, first column
stresses[2, 0]

250

In [11]:
# getting the element in the second row, last column
stresses[1, -1]

400

In [12]:
# getting every element in the first row
stresses[0, :]

array([500, 400, 200])

In [13]:
# getting every element in the 2nd column
stresses[:, 1]

array([400, 100, 400])

In [14]:
# getting the first and third element of the second column
stresses[[0, 2], 1]

array([400, 400])

In [15]:
# getting the last element of the first two rows
stresses[:2, -1]

array([200, 400])

***
## Boolean indexing
Another new piece of functionality with arrays is the ability to select elements with Boolean indexing. This requires you to index with a Boolean array which is the same size as the array of interest. The result will keep all values corresponding to <code>True</code>.

In [16]:
# creating an array of voltages
voltages = np.array([3, 1, 5, 9, 2, 3, 6])

# creating a Boolean array
boolean_index = np.array([True, False, False, True, True, False, False])

# applying Boolean indexing
voltages[boolean_index]

array([3, 9, 2])

You should find the result keeps all the elements that corresponded to True and ignores all the elements that corresponded to False. We can combine this with element-wise operations from the previous page to easily **filter** an array for certain kinds of values.

In [17]:
# filter for voltages less than 4
voltages[voltages < 4]

array([3, 1, 2, 3])

In [18]:
# filter for voltages greater than or equal to 2
voltages[voltages >= 2]

array([3, 5, 9, 2, 3, 6])